# https://travis-ci.org/spyder-ide/spyder

language: python
dist: trusty
sudo: false

matrix:
  include:
    - python: "2.7"
      env: TEST_MODULES=false USE_PYQT=pyqt5
      os: linux
    - python: "2.7"
      env: TEST_MODULES=true USE_PYQT=pyqt4
      os: linux
    - python: "3.5"
      env: TEST_MODULES=false USE_PYQT=pyqt4
      os: linux
    - python: "3.5"
      env: TEST_MODULES=true USE_PYQT=pyqt4
      os: linux
    # This slot test runs our tests only with pip
    # packages
    - python: "3.5"
      env: TEST_MODULES=false USE_PYQT=pyqt5
      os: linux

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - ./continuous_integration/travis/install.sh;

script:
  - |
    if [ "$TEST_MODULES" = "true" ]; then
        ./continuous_integration/travis/modules_test.sh
    else
        if [ "$USE_PYQT" = "pyqt5" ]; then
            ./continuous_integration/travis/test-qt5.sh
        else
            ./continuous_integration/travis/test-qt4.sh
        fi
    fi
