# After changing this file, check it on http://yaml-online-parser.appspot.com/

language: python

env:
  global:
    - MINICONDA_VERSION="latest"
    - MINICONDA_LINUX="Linux-x86_64"
    - MINICONDA_OSX="MacOSX-x86_64"

matrix:
  include:
    # Linux using pip packages
    - python: "2.7"
      env: USE_QT_API=PyQt4 USE_CONDA=false
      os: linux
    - python: "3.4"
      env: USE_QT_API=PyQt4 USE_CONDA=false
      os: linux
    # Linux using conda packages
    - python: "2.7"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "2.7"
      env: USE_QT_API=PyQt5 USE_CONDA=true
      os: linux
    - python: "3.4"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "3.5"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "3.5"
      env: USE_QT_API=PyQt5 USE_CONDA=true
      os: linux

before_install:
  #- sudo apt-get update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - ./continuous_integration/travis_install.sh;
  - if [ "$USE_CONDA" = true ]; then source activate test-environment; fi
  - export PATH="$HOME/miniconda/bin:$PATH";

script:
  - ./continuous_integration/build_test.sh
  - ./continuous_integration/run_test.sh
  - ./continuous_integration/modules_test.sh
