# https://ci.appveyor.com/project/ccordoba12/spyder

environment:
  matrix:
    - PYTHON:         "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH:    "64"
      USE_QT_API:     "PyQt5"

    - PYTHON:         "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH:    "64"
      USE_QT_API:     "PyQt5"

    #- PYTHON:         "C:\\Python35_64"
    #  PYTHON_VERSION: "3.5"
    #  PYTHON_ARCH:    "64"
    #  USE_QT_API:     "PyQt4"

    #- PYTHON:         "C:\\Python27_64"
    #  PYTHON_VERSION: "2.7"
    #  PYTHON_ARCH:    "64"
    #  USE_QT_API:     "PyQt4"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - powershell .\\continuous_integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"

build: false

test_script:
  - "%CMD_IN_ENV% %APPVEYOR_BUILD_FOLDER%\\continuous_integration\\appveyor\\build_test.bat"
  - "%CMD_IN_ENV% %APPVEYOR_BUILD_FOLDER%\\continuous_integration\\appveyor\\run_test.bat"
  - "%CMD_IN_ENV% %APPVEYOR_BUILD_FOLDER%\\continuous_integration\\appveyor\\modules_test.bat"
  - cd %APPVEYOR_BUILD_FOLDER% & python runtests.py
