package:
  name: qtconsole
  version: 4.1

build:
  number: 99

source:
  fn:  qtconsole-4.1.tar.gz
  url: https://pypi.python.org/packages/source/q/qtconsole/qtconsole-4.1.0.tar.gz
  md5: 4f3c43d2d526cbda7760b2c52b5cd79c

requirements:
  build:
    - python
  run:
    - python
    - pyqt5
    - traitlets
    - jupyter_core
    - jupyter_client
    - pygments
    - ipykernel

about:
  home: http://jupyter.org
  license: BSD
  summary: Jupyter Qt Console
