package:
  name: qtconsole
  version: 4.1.1

build:
  number: 99

source:
  fn:  qtconsole-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/q/qtconsole/qtconsole-4.1.1.tar.gz
  md5: e2b0c38344bc584b96b3fe39851645f2

requirements:
  build:
    - python
  run:
    - python
    - pyqt5
    - traitlets
    - jupyter_core
    - jupyter_client
    - pygments
    - ipykernel

about:
  home: http://jupyter.org
  license: BSD
  summary: Jupyter Qt Console
