package:
  name: spyder
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  osx_is_app: True

source:
  git_url: {{ [environ.get('HOME'), '/spy-clone']|join }}
  git_tag: {% if environ.get('TRAVIS_PULL_REQUEST') != 'false' %} {{ ['travis_pr_', environ.get('TRAVIS_PULL_REQUEST')]|join }} {% else %} master {% endif %}

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyqt
    - rope
    - pyflakes
    - jedi            0.8*
    - qtconsole
    - nbconvert
    - pygments
    - sphinx
    - pep8
    - psutil
    - pylint
    - six
    - python.app      [osx]

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
