package:
  name: spyder
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  osx_is_app: True

source:
  git_url: https://github.com/spyder-ide/spyder.git

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyqt
    - rope
    - pyflakes
    - jedi            0.8*
    - qtconsole
    - nbconvert
    - pygments
    - sphinx
    - pep8
    - psutil
    - six
    - python.app      [osx]

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
